export const posts = [
    { id: 1, title: 'Barsukų dainos', content: 'Būsimi dalyviai jau šiandien gali susipažinti su viešai prieinamomis 33 kvietimų temomis, išsamiais reikalavimais laukiamiems sprendiniams. Norintys dalyvauti konkurse privalo turėti partnerių iš kitų ES valstybių ar Norvegijos projektų vykdymui, atitikti kitus reikalavimus. Labai palankios sąlygos dalyvauti EGF yra sudarytos mažoms ir vidutinėms įmonėms (MVĮ), kurioms pirmiausiai yra parengtas atskirtas kvietimas teikti paraiškas. Be to, MVĮ dalyvavimas yra netgi pageidautinas dideliuose konsorciumuose, nes tuomet konsorciumas gali užsitikrinti geresnes finansavimo sąlygas..', date: '2021-01-01', img_url: 'https://upload.wikimedia.org/wikipedia/commons/3/30/%27Honey%27_the_badger_in_daylight.jpg' },
    { id: 2, title: 'Katinų dainos', content: 'Kadangi EGF jau yra vykdomas nuo 2021 m., būsimiems dalyviams būtų labai naudinga ne tik sudalyvauti Lietuvos Krašto apsaugos ministerijos ir EK organizuojamoje EGF informacinėje dienoje bei partnerių paieškos renginyje (kas vyksta gegužės-birželio mėn.), taip pat asmeniškai pasidomėti praeitų metų laimėtojų projektais, konsorciumo struktūromis, šalių pasiskirstymu, projekto finansavimo intensyvumo padidinimo galimybėmis.', date: '2021-01-02', img_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg' },
    { id: 3, title: 'Šunų dainos', content: 'Pirmiausiai reikia pasidžiaugti, kad EK formaliai pradėjo skelbti būsimas kvietimų temas pusmečiu anksčiau nei ankstesniais metais. Taip būsimiems dalyviams yra suteikiama daugiau laiko išsamiai susipažinti su EGF reikalavimais bei organizuoti partnerių paieškas, kas yra ypač aktualu naujiems dalyviams.', date: '2021-01-03', img_url: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg' },
    { id: 7, title: 'Meškėnų pasakos', content: 'Dalyviams bei nacionaliniams sprendimų priėmėjams reikia suvokti, kad EGF tikslas nėra iš karto po MTEP veiklos sukurtus produktus leisti į masinę gamybą. Tam tikslui yra numatytos kitos priemonės bendroje ES gynybos pramonės strategijoje.', date: '2021-01-04', img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Raccoon_in_Central_Park_%2835264%29.jpg' },
    { id: 8, title: 'Mašinų paroda', content: 'Kadangi EGF ES mastu įgyja daugiau patrauklumo nei ES šalių nacionalinės programos gynybos srityje, natūraliai didėja konkurencija. Tai patvirtina didėjantys EK gaunamų projektinių pasiūlymų skaičiai. Tad teikiamos projektų paraiškos turi būti kokybiškai parašytos, aiškios, naudojama iliustracinė medžiaga, kuri padėtų EK vertintojams aiškiau suprasti projekto tikslą ir jo naujumą.', date: '2021-01-05', img_url: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Auto_show_at_the_Toronto_Armouries.jpg' },
    { id: 10, title: 'Turgaus aikštė', content: 'Nacionaliniai dalyviai, teikiantys paraiškas kaip projektų koordinatoriai, turi įvertinti tendenciją, kad daugelis konsorciumų, kurie laimėjo finansavimą projektams, yra sudaryti iš beveik visų ES šalių atstovų. Tai gali būti sėkmės vektorius. EK palankiau vertina tęstinius projektus, tad nacionalinių dalyvių įsitraukimas į rengiamus tęstinus projektus gali garantuoti sėkmę.', date: '2021-01-06', img_url: 'https://upload.wikimedia.org/wikipedia/commons/5/57/The_Moorish_Bazaar.jpg' },
    { id: 14, title: 'Gedimo pilies apžvalga', content: 'Nacionaliniams dalyviams yra privaloma gauti pritarimą iš  Krašto apsaugos ministerijos (KAM) paraiškų teikimui EGF. Kasmet KAM viešai skelbia EGF temų sąrašus, kuriuose yra matomas dalyvavimo interesas. Ministerija išduoda dvejų tipų paramos raštus, kuriais išsakomas palaikymas projektams, o juose nėra įpareigojančių formuluočių. Savaime suprantama, kad pritartiems projektams prižiūrėti iš KAM yra skiriami asmenys bei finansiniai resursai, pvz. padengti komandiruotės išlaidas į kasmetinį projekto susitikimą. Laimėtojams paremti yra sukurta nacionalinė EGF kofinansavimo priemonė.', date: '2021-01-07', img_url: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Gedimino_pilis_by_Augustas_Didzgalvis.jpg' },
    { id: 15, title: 'Traukinių tvarkaraštis', content: 'Siekiant paskatinti nacionalinių dalyvių aktyvesnį dalyvavimą EGF konkurse bei padidinti laimėtojų skaičių, būtų tikslinga įvertinti nacionalinių prioritetinių temų EGF kontekste aktualumą ir jų atsisakyti. Galimai tikslinga yra remtis istoriniu Izraelio pavyzdžiu, kur siekiant paskatinti MTEM gynybos srityje, pradžioje buvo finansuojami visi gynybos startuoliai, o vėliau jau buvo sprendžiama dėl atskirų temų finansavimo, nes išryškėjo rinkos tendencijos, dalyvių kompetencija.', date: '2021-01-08', img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Tren_a_las_nubes_cruzando_Viaducto_la_Polvorilla.jpg' },
    { id: 20, title: 'Arabų ir graikų pasakos', content: 'Neabejotinai nacionalinių dalyvių veiklos EGF teikia naudą tiek krašto apsaugos sistemai, tiek šalies ekonomikai per mokesčius, technologines inovacijas, tarptautinių rinkų atvėrimą. Siekiant padidinti EGF teikiamą naudą Lietuvai, būtų aktualu paskatinti mūsų šalies dalyvius siekti EGF projektų koordinatoriaus vaidmens. Toks  vaidmuo leidžia dalyviams įgyti tarptautinės gynybos projektų valdymo patirties, padidina dalyvio bei Lietuvos matomumą ES mastu.', date: '2021-01-09', img_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Cassim.jpg' },
    { id: 22, title: 'Grikių kruopų nauda jaunam augančiam organizmui', content: 'Šioje geopolitiškai neapibrėžtoje, labai dinamiškoje saugumo situacijoje investicijos į gynybos pramonę yra svarbios. Tad turi būti siekiama mažinti biurokratizmą bei skatinti nacionalinius dalyvius naudotis sukurtais EK mechanizmais gynybos srityje stiprinant nacionalinius MTEP pajėgumus. Tai leis kompanijoms ir institucijoms ilgalaikėje perspektyvoje įsilieti į ginkluotės vertės grandines, pagilinti tarptautinį bendradarbiavimą, susirasti parterių bei plėsti gamybą.', date: '2021-01-10', img_url: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Fagopyrum_esculentum2.jpg' }
];
